(TeX-add-style-hook
 "harmonic-maps"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "sec:org29d0638"
    "sec:org56d0c24"
    "sec:orgaf42f2d"
    "lem:var-energy"
    "prop:holo-harmonic"
    "eq:tangent-exp"
    "sec:orgd687da3"
    "sec:orgb856f17"
    "sec:org5b3844c"
    "sec:orgbf49e8f"
    "sec:org492e9b2"
    "ex:pullback-tangent"
    "lem:calculs-general"
    "eq:laplace-Q"
    "rem:calculs-general"
    "eq:Q-negative"
    "sec:orge42d7b2"
    "sec:general-calcul"
    "sec:org2b0f54d"
    "prop:calculs-pullback-tangent"
    "sec:orgff5bc61"
    "lem:calculs-Q-pullback"
    "sec:orgef3c269"
    "cor:signed-curvature"
    "sec:org00f7819"
    "sec:orgad0ad89"
    "lem:second-fund-form"
    "eq:second-fund-form"
    "sec:orgcc8fdcf"
    "prop:harm-imm-curvature"
    "sec:org03e4f9f"
    "sec:orgfcf0960"
    "thm:Ehresmann-Hermann"
    "eq:g-product"
    "trivalising-map"
    "thm:Hermann"
    "eq:calcul-Hermann"
    "sec:org87c8e11"
    "prop:tension-fibration"
    "sec:orgb5b6454"
    "prop:composition-general"
    "eq:sff-composition"
    "eq:tension-field-composition"
    "prop:compo-immersion"
    "prop:compo-submersion"
    "cor:compo-with-submersion"
    "sec:org6190a72"
    "sec:org69a04d2"
    "eq:loc-heat-flow"
    "thm:eells-sampson"
    "thm:hamilton-bndry-Dirichlet"
    "sec:orgcd4af9e"
    "sec:orgf2de8fe"
    "thm:global-eq"
    "eq:global-heat"
    "thm:unique-nonlinear-heat"
    "eq:dev-sig-unique"
    "eq:sym-red-beta"
    "eq:first-order-w"
    "rem:hamilton-alg-rig"
    "sec:org08246ad"
    "sec:org77cb4c6"
    "thm:den-pot"
    "eq:den-pot-est"
    "thm:den-kin"
    "eq:den-kin-est"
    "eq:den-kin-1"
    "eq:den-kin-2"
    "sec:orgcde4a70"
    "thm:energy-cons"
    "thm:int-den-kin"
    "thm:int-den-pot"
    "cor:bound-2-2")
   (LaTeX-add-bibliographies
    "../res/Stage2018"))
 :latex)

