(TeX-add-style-hook
 "harmonic-maps"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "sec:org9145a27"
    "sec:org81233e1"
    "sec:org8daaba0"
    "lem:var-energy"
    "prop:holo-harmonic"
    "eq:tangent-exp"
    "sec:org0c64434"
    "sec:org978d0ce"
    "sec:org339e674"
    "sec:org20d2747"
    "sec:org1c39d3d"
    "ex:pullback-tangent"
    "lem:calculs-general"
    "eq:laplace-Q"
    "rem:calculs-general"
    "eq:Q-negative"
    "sec:org863dbfd"
    "sec:general-calcul"
    "sec:orgdb06bdf"
    "prop:calculs-pullback-tangent"
    "sec:org805e540"
    "lem:calculs-Q-pullback"
    "sec:org379ca36"
    "cor:signed-curvature"
    "sec:orgc0334f0"
    "sec:org1414732"
    "lem:second-fund-form"
    "eq:second-fund-form"
    "sec:org42bae5b"
    "prop:harm-imm-curvature"
    "sec:orgbfabec4"
    "sec:org16161eb"
    "thm:Ehresmann-Hermann"
    "eq:g-product"
    "trivalising-map"
    "thm:Hermann"
    "eq:calcul-Hermann"
    "sec:orgae5582c"
    "prop:tension-fibration"
    "sec:org929ef26"
    "prop:composition-general"
    "eq:sff-composition"
    "eq:tension-field-composition"
    "prop:compo-immersion"
    "prop:compo-submersion"
    "cor:compo-with-submersion"
    "sec:orgec9b5c0"
    "sec:org6fcf717"
    "eq:loc-heat-flow"
    "thm:eells-sampson"
    "thm:hamilton-bndry-Dirichlet"
    "sec:orgab9af17"
    "sec:orgb597761"
    "thm:global-eq"
    "eq:global-heat"
    "thm:unique-nonlinear-heat"
    "eq:drho-dt"
    "eq:dev-sig-unique"
    "eq:sym-red-beta-before"
    "eq:sym-red-beta"
    "eq:first-order-w"
    "rem:hamilton-alg-rig"
    "sec:org1f4fa53"
    "sec:org3c01090"
    "thm:den-pot"
    "eq:den-pot-est"
    "thm:den-kin"
    "eq:den-kin-est"
    "eq:den-kin-1"
    "eq:den-kin-2"
    "sec:orge212cfb"
    "thm:energy-cons"
    "thm:int-den-kin"
    "thm:int-den-pot"
    "cor:bound-2-2")
   (LaTeX-add-bibliographies
    "../res/Stage2018"))
 :latex)

