(TeX-add-style-hook
 "minimal-immersion-S2"
 (lambda ()
   (LaTeX-add-labels
    "sec:org3f79ab6"
    "sec:org369b6f1"
    "sec:org2619de2"
    "thm:Palais-1"
    "thm:Palais-2"
    "cor:Palais-1-2"
    "sec:org8969f45"
    "rem:tangent-palais"
    "lem:local-isom-e"
    "sec:orgaed99f5"
    "prop:crit-val-1"
    "fact:alg-top-Omega-M-N"
    "thm:3-nontrivial-crit"
    "sec:org431f144"
    "rem:rescal-Euclide"
    "lem:main-est"
    "thm:4-trivial-energy"
    "thm:extension-sacks-uhlenbeck"
    "sec:org42be906"
    "lem:key-sacks-uhlenbeck"
    "rem:topo-C1"
    "prop:2-sacks-uhlenbeck"
    "thm:5-convergence-crit-map"
    "sec:org1ecdb27"
    "thm:6-final-sacks-uhlenbeck"
    "assert:3-star"
    "prop:3-star"
    "rem:final-sacks-uhlenbeck"
    "sec:org1346626")
   (LaTeX-add-bibliographies
    "../res/Stage2018"))
 :latex)

