(TeX-add-style-hook
 "minimal-immersion-S2"
 (lambda ()
   (LaTeX-add-labels
    "sec:org4fcb43b"
    "sec:org4d8655c"
    "sec:orgb908691"
    "thm:Palais-1"
    "thm:Palais-2"
    "cor:Palais-1-2"
    "sec:orgde54354"
    "rem:tangent-palais"
    "lem:local-isom-e"
    "sec:org7be5a37"
    "prop:crit-val-1"
    "fact:alg-top-Omega-M-N"
    "thm:3-nontrivial-crit"
    "sec:org5c54772"
    "rem:rescal-Euclide"
    "lem:main-est"
    "thm:4-trivial-energy"
    "thm:extension-sacks-uhlenbeck"
    "sec:orgfd03f49"
    "lem:key-sacks-uhlenbeck"
    "rem:topo-C1"
    "prop:2-sacks-uhlenbeck"
    "thm:5-convergence-crit-map"
    "sec:orgffd7b44"
    "thm:6-final-sacks-uhlenbeck"
    "assert:3-star"
    "prop:3-star"
    "rem:final-sacks-uhlenbeck"
    "sec:org1da06c8")
   (LaTeX-add-bibliographies
    "../res/Stage2018"))
 :latex)

