#+TITLE: From Busemann function to Cheeger-Gromoll splitting
#+SETUPFILE: ../res/mathsetup.org

We will prove the following result by Cheeger and Gromoll by a slightly modified approach of
A. Besse.

# <<thm:Cheeger-Gromoll>>
#+BEGIN_theorem
#+latex: \label{thm:Cheeger-Gromoll}%
Let $M$ be a complete, connected Riemannian manifold with non negative Ricci curvature. Suppose
that $M$ contains a line then $M$ is isometric to $M'\times \mathbb{R}$ with $M'$ a complete,
connected Riemannian manifold with non negative Ricci curvature.
\end{theorem}
#+END_theorem


* Busemann function

Let $\gamma$ be a geodesic ray. We construct the Busemann function $b$ associated to the ray as
\[
b(x) = \lim_{t\to+\infty}f_t(x) = t - d(x,\gamma(t))
\]
where the limit exists because the sequence $f_t$ is non-decreasing and bounded by
$d(x,\gamma(0))$. The convergence is also uniform in every compact. 


In Euclidean space for example, the Busemann function is the orthogonal projection on $\gamma$. We
will see that in a Riemannian manifold with non negative curvature, the Busemann function will serve
as a projection.


Now with a fixed $x_0\in M$, the tangent vector at $x_0$ of the geodesics connecting $x_0$ and
$\gamma(t)$ is in the unit sphere of $T_xM$, which is compact. Let $X$ be a limit point of these
tangents vectors and pose
\[
b_{X,t}(x) = b(x_0) + t - d(x, C_X(t))
\]
where $C_X(t)$ is the geodesic flow starting at $x_0$ with velocity $X$.

#+BEGIN_remark
- From the construction of $X$, one has $b(x_0) + t = b(C_X(t))$, therefore $b_{X,t} \leq b$ with
equality in $x_0$. We say that $b$ is supported by $b_{X,t}$ at $x_0$. In general a function $f$ is
{\em supported} by $g$ at $x_0$ if $f(x_0)=g(x_0)$ and $f\geq g$ in a neighborhood of $x_0$.
\item $b_{X,t}$ is smooth and a computation in local coordinate gives
  $\Delta b_{X,t} \leq \frac{\dim M - 1}{t}$
- $\|\nabla b_{X,t}\| = 1$
#+END_remark

We also note that it suffices to show that $b$ is harmonic. In fact, from the smoothness one has
$\nabla b(x_0) =\nabla b_{X,t}(x_0)$, which means $\|\nabla b\| = 1$ at every point in $M$. 
For each point $y\in M$, there exists a unique $x$ with $b(x)=0$ and time $t$ when the flow of
$\nabla b$ arrive at $x$. $M$ is therefore homeomorphic to $\bar M\times \mathbb{R}$ by the above
$y\mapsto (x,t)$ map. To see that this map is isometric, it remains to prove that $\nabla b$ is
parallel, which follows from harmonicity of $b$
\[
Ric(\nabla b,\nabla b) = -\|\nabla (\nabla b) \| - (\nabla b).(\Delta b)
\]
we see that $\nabla b$ is parallel if $\Delta b =0$.

#+BEGIN_remark
One can show (see A. Besse) that every gradient field $\nabla b$ of norm 1 at every point is
actually harmonic.
#+END_remark

* Harmonicity
The Busemann function associated to a geodesic ray is subharmonic, it is a consequence of the
following lemma.


# <<lem:1>>
#+BEGIN_lemma
#+LATEX: \label{lem:1}%
  In a connected Riemannian manifold, if a continuous function $f$ is supported at any point $x$ by
  a family $f_\epsilon$ (depending on $x$) with $\Delta(f_\epsilon)\leq \epsilon$, then $f$ can not
  attain maximum (unless when $f$ is constant).
#+END_lemma

#+BEGIN_proof
Given a small geodesic ball $B$, suppose that we have a function $h$ on $B$ with $\Delta h <0$ in $B$ and
$f+h$ attains maximum at $x$ in the interior of $B$. Then $f_\epsilon + h$ also attains maximum at
$x$, which means $\Delta f_\epsilon + \Delta h \geq 0$, which is contradictory.

For the construction of the function $h$, one suppose that $B$ is small enough such that
$f|_{\partial B} \leq max_B f=: f(x_0)$ and equality is not attained at every points in $\partial B$. Then
choose
\[
h = \eta (e^{\alpha \phi} - 1)
\]
with and $\phi(x) = -1$ if $x\in \partial B$ and $f(x) = f(x_0)$, $\phi(x_0) = 0$,
$\nabla \phi \ne 0$ and a large  $\alpha$ such that
\[
\Delta h = \eta (-\alpha^2\| \nabla \phi\| + \alpha \Delta \phi)e^{\alpha \phi}.
\]
#+END_proof


Now for subharmonicity of $b$, given a harmonic function $h$ that coincides with $b$ in the boundary $\partial B$ of a
geodesic ball $B$, then $b-h$ is supported by $b_{X,t} - h$ with $\Delta (b_{X,t}-h) \to 0$ as $t$
tends to $+\infty$, therefore $b-h \leq (b-h)|_{\partial B} = 0$ in $B$. hence $b$ is subharmonic.

#+BEGIN_corollary
The Busemann function of a geodesic ray in a Riemannian manifold $M$ with non-negative Ricci
curvature is subharmonic.
#+END_corollary


Now let $b_+$ be the function previously constructed for the ray $\gamma|_{[0,+\infty[}$ and $b_-$
the Busemann function for the ray $\tilde\gamma|_{[0,+\infty[}$ where $\tilde\gamma(t) =
\gamma(-t)$. Note that $b_+ + b_-\leq 0$ with equality on the line $\gamma$, but the sum is
subharmonic therefore by maximum principle $b_+ = -b_-$ and $b$ is harmonic hence smooth. The
splitting theorem of Cheeger-Gromoll follows.
