#+TITLE: Summary of my stage in Summer 2018
#+AUTHOR: Tien NGUYEN MANH
#+DATE: May 20, 2018
# +STARTUP: indent
# +STARTUP: showstars

#+SETUPFILE: ../res/mathsetup.org
#+INCLUDE: ../res/include.org

#+LATEX:\iffalse
Here is the [[../Stage 2018/main.pdf][memoire]].
#+LATEX:\fi

* Summary

The goal of this part is to give a summary of what will be developed in the next chapters. In brief, we are interested in
maps \( f: M \longrightarrow M' \) between Riemannian manifolds (that to simplify, are
supposed to be compact) that are critical points of the energy functional
\[
 E(f) = \frac{1}{2}\int_M |\nabla f|^2 dV.
\]
By taking first order variation of \( E \), these are maps whose *tension field* \(
\tau(f) \) vanishes. 


** Deformation using nonlinear heat equation.

The approach of cite:eells_harmonic_1964 is to prove that, if the target space is
negatively curved, then any smooth map \( f_0: M \longrightarrow M' \) can be deformed to a
harmonic map using the gradient descent equation, that is to show the equation
\begin{equation}
\label{eq:intro:1}
\begin{cases}
\frac{df_t}{dt} = \tau(f_t)\\
\restr{f}{t=0} = f_0
\end{cases}
\end{equation}
We will prove that if \( M' \) is negatively curved then this PDE admits a globally defined smooth
solution \( f_t \) and that \( f_{\infty}:=\lim_{t\to \infty} f_t \) in \( C^\infty \) is
a harmonic map.

The resolution of eqref:eq:intro:1 can be organised in 3 steps:
1. Find the global equation. We will find a global frame of \( M' \) and express
   \( f \) in this frame, so that instead of solving for a map, we will have to solve for functions.
2. Study linear PDEs on manifolds. The equation, expressed in local coordinates, is a nonlinear heat equation, i.e. other
   than a heat operator, it has a quadratic term. Short-time existence and regularity for eqref:eq:intro:1 follows from /standard/ results of
   parabolic equation.
3. Prove long-time existence. In order to use continuity method, we will have to prove
   that \( W^{k,p} \)-norms of the solution \( f_t \) do not explode. This will be
   established first in the case \( W^{2,2} \) using physical quantities, namely the
   potential energy \( E \) and the kinetic energy \( K \). The general case is proved
   from the \( W^{2,2} \) estimate using Gårding's inequality and Comparison theorem for
   parabolic equation. 

The hypothesis of negative curvature is only used to establish the energy
estimates. During deformation, the rate of potential energy can be calculated as: 
\[
 \frac{d e(f_t)}{dt}= -\Delta e(f_t) - |\beta(f_t)|^2 - \left\langle \Ric(M) \nabla_v
f_t,\nabla_v f_t \rangle + \langle \Riem(M') (\nabla_v f_t,\nabla_w f_t)\nabla_v
f_t,\nabla_w f_t \right\rangle
\]
and the kinetic energy as:
\[
 \frac{d k(f_t)}{dt}= -\Delta k(f_t) - \left|\nabla \frac{\partial f_t}{\partial t}\right|^2 +
\left\langle \Riem(M') (\nabla_v f_t,\frac{\partial f_t}{\partial t})\nabla_v
f_t,\frac{\partial f_t}{\partial t} \right\rangle
\]
Therefore if all sectional curvatures of \( M' \) are negative, these rates can be
controlled and the energies are guaranteed not to explode.

** Existence using Morse-Palais-Smale theory.
We also give a less detailed review of the work by Sacks and Uhlenbeck
cite:sacks_existence_1981. This approach uses an approximating family \(
E_\alpha \) of the energy functional \( E \) whose critical functions in \( W^{1,2\alpha} \) can be easily proved
to exist using Morse-Palais-Smale theory. We then try to prove that the critical sequence
\( C^1 \)-converges to a nontrivial limit. 

As a concrete result, the authors proved,
using an extension theorem for harmonic maps on surface and a suitable covering of \(
M \) by small discs on which the energy \( E \) is sufficiently small, that if
the fundamental group \( \pi_k(M') \) is nontrivial for a certain \( k\geq 2 \), or
equivalently, if the universal covering \( \tilde M' \) of \( M' \) is not contractible,
then there exists a nontrivial harmonic map from \( \mathbb{S}^2 \) to \(  M' \).


#+LATEX:\iffalse
bibliographystyle:alpha
bibliography:../res/Stage2018.bib
#+LATEX:\fi
