#+TITLE: Symmetric spaces and Lie groups
#+SETUPFILE: ../res/mathsetup.org

* Symmetric space
By the sake of de Rham decomposition, we now focus more in Riemannian manifold with irreducible
holonomy representation. The theory of Lie groups allows us to understand symmetric spaces.


#+BEGIN_definition
A Riemannian manifold $M$ is called /symmetric/ if for every $x\in M$, there exists a isometry
$s_x$ of $M$ such that $x$ is an isolated fixed point and $s_x^2=Id$.
#+END_definition


Let $x\in M$ and $v\in T_xM$, we note by $\exp_x(v)$ the point of distance $|v|$ in the geodesic
starting in $x$ with velocity $v/|v|$. We remark that any isometry $s_x$ with $s_x^2=Id$ and $x$ as isolated fixed
point satisfies 
\begin{equation}
  \label{eq:sxreverse}
s_x(\exp_x(v)) = \exp_x(-v)
\end{equation}
In fact the eigenvalues of $T_xs_x$ have to be $1$ or $-1$, but as $x$ is an isolated fixed point
one has $T_xs_x = -Id$. Then $s_x$ as an isometry sends the geodesic starting at $x$ with velocity
$v$ to one starting at $s_x(x)=x$ with velocity $T_xs_x.v = -v$ and we have \eqref{eq:sxreverse}.


Equation \eqref{eq:sxreverse} tells us that $s_x$ is a reflection of center $x$ on every geodesic
passing by $x$. We can now compose two reflection $s_x,s_y$ to form a translation on the geodesic
connecting $x$ and $y$. This shows that a symmetric space is complete and the group of isometries
of the form $s_x\circ s_y$ acts transitively on $M$.

#+ATTR_LATEX: :options [Symmetric space]
#+BEGIN_theorem
<<thm:symmetric-space>> 
Let $M$ be a symmetric Riemannian manifold then $M$ is complete. Fix $x_0\in
M$, let $G$ be the group generated by the isometries of form $s_x\circ s_y,\ x,y\in M$ and $H$ the
subgroup containing elements of $G$ that fix $x_0$, then $G$ is Lie subgroup of $Iso(M)$ connected
by arc, $H$ is a closed Lie subgroup of $G$ and $M$ is isometric to $G/H$. Moreover the holonomy
group of $M$ is $H$.
#+END_theorem

#+BEGIN_remark
In general, for a Lie group $G$ and a closed Lie subgroup $H$, if $G$ has a metric left-invariant by
$G$ and right-invariant by $H$ (i.e. the metric on $\frak{g}$ is invariant by action of $H$ by
adjoint) then 
\[ 
\frak{g} = \frak{h} \oplus^\perp \frak{m},\quad [\frak{h},\frak{m}]\subset \frak{m}
\] 
But if $G/H$ is symmetric then one has the following extra information 
\[
[\frak{m},\frak{m}]\subset \frak{h} 
\] 
The second condition is quite strong and allowed E. Cartan to
classify all such pairs $(\frak{g},\frak{h})$.
#+END_remark

* Locally symmetric space
The previous results can be extended to locally symmetric spaces.

#+BEGIN_definition
Let $M$ is a Riemannian manifold, the followings are equivalent
1. For every $x\in M$, there exists a neighborhood $U$ of $x$ and an isometry $s_x:\
   U\longrightarrow U$ such that $s_x^2=Id$ and $x$ is the unique fixed point of $s_x$.
2. The curvature tensor $R$ satisfies
\[
\nabla R = 0
\]
In this case, $M$ is called  /locally symmetric/.
#+END_definition

#+ATTR_LATEX: :options [Locally symmetric space]
#+BEGIN_theorem
<<thm:locally-sym-space>>
Let $M$ be a locally symmetric Riemannian manifold, then there exists a unique symmetric simply
connected Riemannian manifold $N$ such that $M$ and $N$ are locally isometric, i.e. for every
$x\in M$ and $y\in N$, there exists neighborhoods $U$ of $x$ and $V$ of $y$ that are isometric.
#+END_theorem

As a result, the holonomy group can not tell the difference between a symmetric and a locally
symmetric manifold.

* Appendice: Group of isometries as Lie group

Every topological subtleties should be explained in this appendice. We claim, with
Montgomery-Zippin, /Transformation groups/ as reference a general result 

#+ATTR_LATEX: :options [faithful + locally compact $\geq$ Lie]
#+BEGIN_theorem
<<thm:faithful-locally-compact>>
Let $G$ be a group acting faithfully on a connected manifold $M$ of class $C^k$ such that each
action is $C^1$. Then $G$ is a Lie group and the map $G\times M\longrightarrow M$ is $C^1$.
#+END_theorem

Then the problem becomes a topological one: to prove that the underlying group is locally
compact. Note that we equipe with _a group_ of isometries with the *compact-open topology*,
 as $M$ is locally compact and hence second-countable (i.e. the topology admits a countable
base), we see that a group of isometries is also second-countable. It suffices to prove the
second-countability for _the group_ of (all) isometries. The detail can be found in
Kobayashi-Nomizu's /Foundations of differential geometry/ (Volume I, Theorem 4.7).

#+BEGIN_theorem
<<thm:isometry-locally-compact>>
Let $M$ be a connected, locally-compact metric space and $G$ be the group of isometries of
$M$, then
1. $G$ is locally compact.
2. $G_a$ the subset of isometries fixing a point $a\in M$ is compact.
3. If, in addition, $M$ is compact then $G$ is also compact.
#+END_theorem
