#+TITLE: Two theorems of Hartogs
#+SETUPFILE: ../res/mathsetup.org
#+INCLUDE: ../res/include.org

* Hartogs' theorem for subharmonic function
The first Hartogs theorem concerns the convergence of harmonic functions. It says that
under certain conditions, the convergence, apriori pointwise, is actually uniform on every compacts.
#+ATTR_LATEX: :options [Hartogs on subharmonic functions]
#+ATTR_HTML: :id thm:hartogs-subhar :btit (Hartogs on subharmonic functions) 
#+BEGIN_theorem
#+LATEX: \label{thm:hartogs-subhar}
Let \( \Omega \) be a domain and \( u_k \in SH(\Omega) \) a sequence of subharmonic
function such that
1. Uniformly bounded on compacts: \( \restr{u_k}{K} < M_K \).
2. Pointwise limit is continuous: \( \limsup_k u_k(x) = C \)
Then for every \( K\subset \Omega \) compact and \( \varepsilon >0 \), there exists \(
N(K,\varepsilon) >0 \) such that \( u_k < C+ \varepsilon \) for all \( k > N(K,\varepsilon) \)
#+END_theorem

#+BEGIN_proof
By covering \( \Omega \) with an increasing sequence of compact \( K_n \) that \( K_n
\Subset Int(K_{n+1}) \), one can suppose that \( u_k<M \) on \( \Omega \). One can also
suppose that \( M=0 \). Note that it
suffices to prove that for any \( x\in \Omega \), there exists \( N(x,\varepsilon) \) such
that \( u_k < C+\varepsilon \) on a neighborhood \( U_x \) of \( x \) for all \( k>N(x,\varepsilon) \), then the conclusion
follows by compactness of \( K \).

One has \( \lim_{k\to +\infty}\int_{B(x,R)}u_k = C|B(R)| \) by monotone convergence, so
\( \int_{B(x,R)}u_k < (C + \varepsilon) |B(R)|\) for \( k> N_1(x,\varepsilon) \). For any
\( r\ll R \) and \( y\in B(x,r) \) one has \( \int_{B(y, R+ r)}u_k \leq \int_{B(x,R)}u_k <
(C+\varepsilon)|B(R)|\). Therefore
\[
u_k(y)\leq (C+\varepsilon)\frac{|B(R)|}{|B(R+r)|}\leq C+2\varepsilon\qquad \forall r \ll
R, k>N_1(x,\varepsilon)
\]
which shows that \( u_k < C+2\varepsilon \) for in a small neighborhood \( B(x,r) \) of \( x \). 
#+END_proof

#+BEGIN_remark
The Theorem ref:thm:hartogs-subhar above can be easily generalized by replacing the
constant \( C \) by a continuous function \( f \).
#+END_remark


* Hartogs theorem of separately holomorphicity
The second result of Hartogs that I want to present here is about the founding notion of
holomorphicity for several complex variables.

#+ATTR_LATEX: :options [Hartogs for separate holomorphicity]
#+ATTR_HTML: :id thm:hartogs-separate-holo :btit (Hartogs for separate holomorphicity) 
#+BEGIN_theorem
#+LATEX: \label{thm:hartogs-separate-holo}
A function \( f \) separately holomorphic on each variable then \( f \) is smooth and
hence is completely holomorphic
#+END_theorem

The strategy is to establish the following steps:

1. \( f \) is locally bounded.
2. \( f \) is continuous.
3. \( f \) is smooth, hence is completely holomorphic.

The second and third steps are not difficult. In fact when one knows that \( f \) is
locally bounded, one can prove that \( f \) is continuous by Schwartz lemma on each
variable with appropriate scaling.
\[
f(z_1,\dots, z_i,\dots \xi_n ) - f(z_1,\dots, \xi_i,\dots, \xi_n)
\leq |1-\overline{f(\dots,z_i,\dots)}f(\dots, \xi_i, \dots)|\left| \frac{z_i - \xi_i}{1 -
z_i\bar \xi_i} \right|\quad \forall |z_i|,|\xi|<1, |f|<1 
\]

When \( f \) is continuous, one may refind Cauchy integral formulae and differentiability
follows by dominated convergence.

So the remaining point is to prove that \( f \) is locally bounded, which can be done
using Baire theorem and the first Hartogs result, Theorem ref:thm:hartogs-subhar.

** Application of Baire theorem.
We will prove Theorem ref:thm:hartogs-separate-holo by induction on the dimension \( n
\). We can therefore suppose that with the last variable \( z_n \) fixed, the function is
completely holomorphic on the \( n-1 \) first variables. Fix a closed \( n \)-polydisc
\(\mathbb{D}^n\ni x=0 \), denote \[ W_L = \{ (z_1,\dots,z_{n-1})\in
\mathbb{D}^{n-1}:\quad |f(z_1,\dots,z_n)|\leq L\quad \forall z_n\in \mathbb{D}^1\} \] then
1. \( \bigcup_{L\in \mathbb{N}} W_L = \mathbb{D}^n \) since for fixed \( (z_1,\dots,z_{n-1})\in
   \mathbb{D}^{n-1} \), the function \( f \) is continuous on \( z_{n-1} \).
2. Each \( W_L \) is closed since for fixed \( z_n \), the function \( f \) is continuous
   on \( n-1 \) first variables.
Therefore by Baire theorem, there exists \( L \) large enough such that \( W_L \) contains
an open set of \( \mathbb{D}^{n-1} \). Therefore there exists a strip \( U_{n-1}\times
\mathbb{D}\subset \mathbb{D}^n \) on which the function \( f \) is holomorphic.

We will extend this strip using the following lemma
#+ATTR_HTML: :id lem:ext-strip
#+BEGIN_lemma
#+LATEX: \lem{lem:ext-strip}
Let \( f \) be a separately holomorphic function defined on a neighborhood of \( \mathbb{D}^n \) such that
1. \(f \) is continuous on a neighborhood of the strip \( \mathbb{D}_\rho\times\dots\times \mathbb{D}_\rho\times \mathbb{D} \),
2. \( f \) is completely holomorphic on the first \( n-1 \) variables when the last one is fixed,
then \( f \) is completely holomorphic on \( \mathbb{D}^n \)
#+END_lemma

This lemma can be proved using the series decomposition of \( f \). 

** Analysis of series decomposition.
Since \( f \) is completely holomorphic on the first \( n-1 \) variables when \( z_n
\) is fixed, one has
\[
f(z_1, \dots, z_n) = \sum_\alpha a_\alpha(z_n)z^\alpha,\qquad a_\alpha(z_n)=
\partial^{\alpha} f(0,z_n)/\alpha! \text{ is holomorphic in } z_n
\]
Then the fact that for fixed \( z_n \), the holomorphic function \( f(z', z_n) \) is
well-defined on \( z'\in \mathbb{D}^{n-1} \) shows
that
\begin{equation}
\label{eq:1}
 \limsup_{|\alpha| \to \infty}|a_\alpha(z_n)|^{1/|\alpha|} \leq 1.
\end{equation}

Moreover, Cauchy integral on \( \mathbb{D}_\rho\times\dots\times \mathbb{D}_\rho\times
\mathbb{D} \) shows that
\begin{equation}
\label{eq:2}
|a_\alpha(z_n)| = |\partial^{\alpha} f(0,z_n)|/\alpha! \leq \frac{1}{\rho^{|\alpha|}} M
\end{equation}

where \( M \) is an upper bound of \( |f| \) on the strip.

Let \( u_\alpha = \frac{1}{|\alpha|}\log|a_\alpha| \) be a subharmonic function of \( z_n\in \mathbb{D} \),
eqref:eq:1 and eqref:eq:2 show that \( \limsup_{|\alpha|\to \infty} u_\alpha\leq 0 \) and
\( u_\alpha \leq \frac{1}{|\alpha|}\log M -\log\rho \) hence uniformly bounded.

By Theorem ref:thm:hartogs-subhar, one has \(|a_\alpha(z_n)|^{1/|\alpha|} \leq
1+\varepsilon \) for \( |\alpha| \) sufficient large. Letting \( \varepsilon \to 0 \), one
sees that the series converge normally in the interieur of \( \mathbb{D}^{n-1} \), hence
by Cauchy-Montel the limit \( f \) is holomorphic in the interieur of \( \mathbb{D}^n \).


