
#+SETUPFILE: ../res/mathsetup.org

#+BEGIN_EXPORT html
\(
\newcommand{\re}{\mathop{\rm Re}\nolimits}
\newcommand{\im}{\mathop{\rm Im}\nolimits}
\newcommand{\coker}{\mathop{\rm coker}\nolimits}
\newcommand{\supp}{\mathop{\rm supp}\nolimits}
\newcommand{\ord}{\mathop{\rm ord}\nolimits}
\newcommand{\Spec}{\mathop{\rm Spec}\nolimits}
\newcommand{\vol}{\mathop{\rm vol}\nolimits}
\newcommand\restr[2]{{\left.#1\right|_{#2}}}
\newcommand{\transp}{\mathop{\rm \,^t}\nolimits}
\newcommand{\sff}{\mathop{\rm I\!I}\nolimits}
\newcommand{\tr}{\mathop{\rm Tr}\nolimits}
\newcommand{\const}{\mathop{\rm const }\nolimits}
\newcommand{\lcm}{\mathop{\rm lcm}\nolimits}
\newcommand{\gcd}{\mathop{\rm gcd}\nolimits}
\newcommand{\Ric}{\mathop{\rm Ric}\nolimits}
\newcommand{\Riem}{\mathop{\rm Riem}\nolimits}
\newcommand{\Enorm}{\mathop{\mathcal{E}_{\rm norm}}\nolimits}
\newcommand{\Anorm}{\mathop{\mathcal{A}_{\rm norm}}\nolimits}
\)
#+END_EXPORT


* Variation of renormalised quantities <2018-11-26 Mon>   :noexport:

Although we had a formula for the different \( \Enorm- 2\Anorm \)
\[
 \Enorm-2\Anorm = \frac{1}{4}\int_\Sigma \frac{|q(f,[h_0],g)|^2_{h}}{\tr_h f^*g + 2\sqrt{\det_h
f^* g}}dV_h
\]
it is not straightforward to differentiate this formula to find \( \frac{d}{dt}\Enorm
(f_t) - \frac{d}{dt}2\Anorm (f_t(\Sigma)) \).

#+ATTR_LATEX: :options [Variation of renormalised quantities]
#+ATTR_HTML: :id prop:var-var :btit (Variation of renormalised quantities) 
#+BEGIN_proposition
#+LATEX: \label{prop:var-var}
One has
\begin{equation}
\label{eq:var-var}
\frac{d}{dt}\Enorm(f_t,h_0,g) - \frac{d}{dt}2\Anorm(f_t(\Sigma)) = \frac{1}{4}\int_\Sigma
\langle \re q(f_0,[h_0],g), \frac{dh_t}{dt} \rangle_{h_0} dV_{h_0}
\end{equation}
In particular, at harmonic map \( f_0 \) who satisfies stronger boundary condition (then \( h_0 \) is
conformal to \( f^*g \)), the two variation coincide.
#+END_proposition

We will start by distinguishing the two notion in classical context. Let \( \Sigma_t \) be a
family of surface in an ambiant space \( M \), then one way to look at them is as a family
of immersions from a model surface \( \Sigma \) to \( M \).
\[
f_t:\Sigma \longrightarrow M
\]
equip \( \Sigma \) with a metric \( h \), the energy functional of \( f_t \) is 
\[
 E(f_t,h, g) = \int_\Sigma \tr_h f_t^*g\ dV_h
\]
which generalises the area functional \( A(f_t,g) = \text{area}(f_t(\Sigma)) =
\frac{1}{2}E(f_t,f_t^* g,g) \).

However, by variation of energy, we mean
\(
 \frac{d}{dt}E(f_t,h,g)
\)
which is different from the variation of area \(
\frac{d}{dt}A(\Sigma_t)=\frac{1}{2}\frac{d}{dt}E(f_t,h_t,g)\) where \( h_t = f_t^*g \).

The two variations are related by the following formula:
\begin{equation}
\label{eq:var-var-1}
\frac{d}{dt}E(f_t,h_t,g) = \frac{d}{dt}E(f_t,h_0,g) + \frac{1}{4}\int_\Sigma \left\langle \re q(f_0,[h_0],g), \frac{d h_t}{dt} \right\rangle_{h_0}dV_{h_0}
\end{equation}
where \( q(f_0,[h_0],g) = \langle \frac{\partial f_0}{\partial z}, \frac{\partial
f_0}{\partial z} \rangle_g dz\otimes dz \) is the *quadratic differential* of \( f \) as a
map from the Riemann surface \( (\Sigma,[h_0]) \) to a Riemannian manifold \( (M,g) \).

In order to prove eqref:eq:var-var, just note that 
\begin{align*}
\frac{d}{dt}(\Enorm - 2\Anorm) &= \frac{d}{dt}\lim_{\epsilon\to 0}(E_\epsilon - 2A_\epsilon)\\
		      	      &= \lim_{\epsilon\to 0}\frac{d}{dt} \int_{\Sigma_\epsilon(f_t)} \tr_{h_0}f_t^* g dV_{h_0} - \tr_{h_t}f_t^* g dV_{h_t} \\
			      &= \lim_{\epsilon\to 0}\frac{d}{dt} \int_{\Sigma_\epsilon(f_t)} \left(\tr_{h_0}f_0^* g - \tr_{h_0}f_0^* g \frac{dV_{h_0}}{dV_{h_0}}\right) dV_{h_0} + \lim_{\epsilon\to 0}\frac{d}{dt} \int_{\Sigma_\epsilon(f_0)} \left(\tr_{h_0}f_t^* g - \tr_{h_t}f_t^* g \frac{dV_{h_t}}{dV_{h_0}}\right) dV_{h_0} \\
			      &= \lim_{\epsilon\to 0} \frac{1}{4} \int_{\Sigma_\epsilon(f_0)} \left\langle \re q(f_0,[h_0],g), \frac{dh_t}{dt} \right\rangle_{h_0} dV_{h_0}\\
			      &= \frac{1}{4} \int_{\Sigma} \left\langle \re q(f_0,[h_0],g), \frac{dh_t}{dt} \right\rangle_{h_0} dV_{h_0}
\end{align*}
where we applied eqref:eq:var-var-1 in the 4th equality.



* First variation of renormalised energy. <2018-10-26 Fri>  :noexport:
** The results.

  I will start by writing down the result before giving the proofs. Let \( (\Sigma,i) \)
  be a Riemann surface and \( (M,g) \) be an asymptotically hyperbolic Riemannian
  four-manifold. We are interested in critical points of renormalised energy \( \Enorm \)
  because these maps form a special class among harmonic maps whose energy is critical to all
  pertubation (and not just compact pertubation).

  Even though we obtained an explicit formula for renormalised energy where a density appears
  \[
  \Enorm = -4\pi\chi + \int_\Sigma \left[ 2K(f^*g)\sqrt{{\rm det}_h f^*g} + \tr_h f^*g \right] dA_h,
  \]
  it is not easy to compute its variation directly from it. The following
  approach gives us a formula that although is not explicit, allows us to see the
  following phenomenon.
  #+ATTR_LATEX: :options [Critical points of \(\Enorm\) = Harmonic + good germ on the boundary]
  #+ATTR_HTML: :id thm:crit-Enorm-bndry-germ :btit (Critical points of \(\Enorm\) = Harmonic + good germ on the boundary) 
  #+BEGIN_theorem
  #+LATEX: \label{thm:crit-Enorm-bndry-germ}
  Let \( f: (\Sigma,i) \longrightarrow (M,g) \) be a harmonic map from a Riemann surface \( \Sigma \) to
  a AH Riemannian four-manifold \( M \) such that \( q(f)_{\bar g} = 0 \) on \( \partial\Sigma \). There is a boundary quantity \( \mathcal{B}_2(f)
  \) that only concerns the germ of \( f \) on \( \partial\Sigma \) such that:
  #+BEGIN_CENTER
  \( f \) is critical to \( \Enorm \) if and only if \( \mathcal{B}_2(f) = 0 \).
  #+END_CENTER
  #+END_theorem

  We know that the \( \epsilon \)-energy must be writen as
  \[
   E_\epsilon (f) = \frac{1}{\epsilon} {\rm length}(\gamma) + \Enorm + O(\epsilon)
  \]
  where \( \gamma\) is the boundary curve of \( f\) and the length is taken under the
  metric \( \bar g \). Now given a pertubation \( \{f_t\} \) of \( f_0 \), we can recover
  the variation of \( \Enorm \) by looking at the \( O(1) \) term of \(
  \frac{dE_\epsilon}{dt}(f_t) \). It turns out that in order to compute the variation of
  \( E_\epsilon \), we only need to do the following 2 tasks:
  - Extend the computation made by Eells-Sampson cite:eells_harmonic_1964 to manifold with boundary.
  - Take care of the variation of the domain of integration \( \Sigma_\epsilon(f_t):=
    f_t^{-1}(r\geq\epsilon) \) which also depends on \( t \) where \( r \) is the boundary
    defining function (bdf).

  #+ATTR_LATEX: :options [Variation of \( E_\epsilon \)]
  #+ATTR_HTML: :id prop:var-Eeps :btit (Variation of \( E_\epsilon \)) 
  #+BEGIN_proposition
  #+LATEX: \label{prop:var-Eeps}
  For any pertubation \( \{f_t\} \) of \( f: (\Sigma,\partial\Sigma,i) \longrightarrow (M,\partial M,g) \), one has
  \begin{equation}
  \label{eq:var-Eeps}
  \frac{d}{dt}E_\epsilon(f_t) = \int_{\Sigma_\epsilon(f_0)} \left\langle \tau(f_0), \frac{df_t}{dt} \right\rangle_g dV_h + \frac{1}{\epsilon^2}\int_{\partial\Sigma_\epsilon(f_0)}\left \langle 2 \frac{\partial f_0}{\partial n} + \frac{\nabla^g r(f_0)}{|d(r\circ f_0)|_h} \tr_h (f_0^*g) , \frac{df_t}{dt}\right \rangle_{\bar g} ds_h  
  \end{equation}
  where 
   - \( h \) is a metric in the conformal class \( i \) of \( \Sigma \),
   - \( \frac{\partial}{\partial n} \) is the \( h \)-unit normal vector of \( \partial\Sigma_\epsilon(f_0) \) in \(
     \Sigma_\epsilon(f_0) \),
   - \( \tau(f_0) \) is the tension field of \( f_0 \) with respect to the metric \( h \)
     on \( \Sigma \) and \( g \) on \( M \).
  Denote \( \mathcal{B} := \int_{\partial\Sigma_\epsilon(f_0)}\left
  \langle 2 \frac{\partial f_0}{\partial n} + \frac{\nabla^g r(f_0)}{|d(r\circ f_0)|_h}\tr_h(f_0^*g)  ,
  \frac{df_t}{dt}\right \rangle_{\bar g} ds_h =: \mathcal{B}_0 + \mathcal{B}_1 \epsilon +
  \mathcal{B}_2 \epsilon^2 + O(\epsilon^3) \) then 
   - \( \mathcal{B}_i \) only depends on the germ of \( f_0 \) on \( \partial\Sigma \)
   - \(\mathcal{B}_0 = 2\int_{\partial\Sigma}\left \langle \frac{\partial f_0}{\partial n} +
     \frac{\nabla^{\bar g}r(f_0)}{|\nabla^{\bar g}r(f_0)|_{\bar g}}, \frac{df_t}{dt}\right
     \rangle_{\bar g} ds_h = 0\) where \( n \) is the \( f^* \bar g \)-normal vector of \( \Sigma \) on
     the boundary.
   #+END_proposition

  As a straightforward consequence, one has
  #+ATTR_LATEX: :options []
  #+ATTR_HTML: :id prop: :btit () 
  #+BEGIN_proposition
  #+LATEX: \label{prop:}
  Given a map \( f: (\Sigma, \partial\Sigma, i) \longrightarrow (M, \partial M, g) \), then:
   1. \( f_0 \) is harmonic and \( \mathcal{B}_2(f_0) = 0 \) if and only if \( f_0 \) is a
      critical point of \( \Enorm \).
   2. The first variation of \( \Enorm \) can be writen as:
      \begin{align*}
      \frac{d \Enorm}{dt}(f_t) &= \int_{\Sigma} \left\langle \tau(f_0),
      \frac{df_t}{dt} \right\rangle_g dV_h  \\ &+
      \lim_{\epsilon\to 0} \frac{1}{\epsilon^2} \left
      [\int_{\partial\Sigma_\epsilon(f_0)}\left \langle 2
      \frac{\partial f_0}{\partial n} + \frac{\nabla^g r(f_0)}{|d(r\circ f_0)|_h} \tr_h(f_0^*g)  ,
      \frac{df_t}{dt}\right \rangle_{\bar g} ds_h +  \int_{\Sigma_\epsilon(f_0)} \left
      \langle \nabla^{\bar g}_{\dot\gamma} \frac{\dot\gamma}{|\dot\gamma|_h} ,
      \frac{df_t}{dt}\right \rangle_{\bar g}\right]      
      \end{align*}

      where \( \gamma \) is the boundary curve of \( f \), \( \frac{\partial}{\partial n}
      \) is the \( h \)-unit normal vector of \( \partial\Sigma_\epsilon \) in \( \Sigma_\epsilon \).
  #+END_proposition
  
  
** Proofs.
   We [[ref:Eells-Sampson-bndry]] knew that the variation of energy functional can be represented by the tension field, in
   case of manifolds with boundary, we obtain an additional term from Stokes formula: 
   \begin{align}
      \frac{d}{dt}E_\epsilon(f_t) &= \frac{d}{dt}\int_{\Sigma_\epsilon(f_0)} \tr_h (f_t^* g) +   \frac{d}{dt}\int_{\Sigma_\epsilon(f_t)} \tr_h (f_0^*g)\\
      				  &= \int_{\Sigma_\epsilon(f_0)} \left \langle \tau(f_0), \frac{df_t}{dt} \right \rangle_g dV_h + 2\int_{\partial\Sigma_\epsilon(f_0)} \left \langle \frac{\partial f_0}{\partial n}, \frac{df_t}{dt}\right \rangle_g + \frac{d}{dt} \int_{\Sigma_\epsilon(f_t)} \tr_h( f_0^* g) dV_h
   \end{align}
   Equation eqref:eq:var-Eeps is a straightforward application of the
   following lemma for \( \Omega_t = \Sigma_\epsilon(f_t)\), \(F=\tr_h(f_0^* g) \) and \( r_t = r\circ f_t \).

   #+ATTR_LATEX: :options [Riemannian Cavalieri]
   #+ATTR_HTML: :id lem:var-domain :btit (Riemannian Cavalieri) 
   #+BEGIN_lemma
   #+LATEX: \label{lem:var-domain}
   Let \( \Omega \) be a domain in \( \Sigma \) and  \( \{r_t\}_{t=\overline{0,1}} \) be a familly of functions on \( \Omega \) where \(
   dr_t \) are non-zero and \( \Omega_t\subset \Omega \) be subdomains of \( \Omega \) defined by \( \Omega_t =
   \{r_t \geq \epsilon\}\). Then for any function \( F \) on \( \Omega \), one has
   \[
   \restr{\frac{d}{dt}}{t=0}\int_{\Omega_t}F dV_h = \int_{\partial\Omega_0}
   \frac{r_1}{|\nabla^h r_0|_h}F ds_h
   \]
   where \( r_1 = \restr{\frac{dr_t}{dt}}{t=0} \).
   #+END_lemma

   
   #+BEGIN_proof
   Let us prove the lemma in case \( \Omega_t \) only has one connected component with
   non-empty interior, since
   the number of such components does not change for \( t \) near 0 (this is because
   \( r_0 \) has no critical point in \( \Omega \)). Let
   us also suppose that \( r_1 \geq 0 \) meaning that the domain \( \Omega_t \)
   becomes bigger as \( t \) increases from \( 0 \). This is because one can always
   partition the curve \(\gamma = \partial\Omega_0 \) into pieces where \( r_1>0, r_1 <0 \) or \( r_1=0 \)
   and the area difference of pieces touching the \( r_1=0 \) parts is of \( O(t^2) \). 

   The difference \( \Omega_t\setminus \Omega_0 \) is the region where \( \epsilon -r_1 t+
   O(t^2)\leq r_0 \leq \epsilon \), therefore \( \Omega_t\setminus \Omega_0 \) is of \(
   O(t^2) \) difference from the region \( \Phi_t = \{ \exp_{\gamma(s)}\frac{\theta r_1\nabla^h
   r_0}{|\nabla^h r_0|^2}:\theta \in[0,t], s\in[0,1] \} \). Therefore
   \[
   \restr{\frac{d}{dt}}{t=0}\int_{\Omega_t}F dV_h
   =\restr{\frac{d}{dt}}{t=0} \int_0^t \int_{\gamma} F \frac{r_1}{|\nabla^h r_0|_h} \text{vol }ds_h d\theta = \int_{\gamma} F\frac{r_1}{|\nabla^h r_0|_h} ds_h .
   \]
   where \(  \frac{r_1}{|\nabla^h r_0|_h}\text{vol}(s,\theta) ds_h d\theta \) is the
   pullback of the volume form by exponential map
   \( (s,\theta)\mapsto \exp_{\gamma(s)} \frac{\theta r_1\nabla^h r_0}{|\nabla^h r_0|_h^2}
   \), so \( \text{vol}(s,0) = 1 \).
   #+END_proof
   



* Another formula for \( \Enorm\). Harmonic maps are critical points of \( \Enorm \) under stronger vanishing condition. :noexport: 
** Review of Alexakis--Mazzeo. Another formula of \( \Enorm \)
Alexakis and Mazzeo obtained a formula for renormalised area \( \Anorm \) by rewriting 
\[
 A_\epsilon = \int_{\Sigma_\epsilon}1 dA = \int_{\Sigma_\epsilon}(1 + K)dA - \int_{\Sigma_\epsilon}KdA
\]
where \( K \) is the Gauss curvature of the restriction of the metric \( g \) on \( \Sigma
\). They then 
- use Gauss--Codazzi formula and Ei
nstein equation to rewrite \( 1+K \) in term of
  second fundamental form to prove that \( \int_{\Sigma_\epsilon}(1+K)dA \) converges to a
  finite limit as \( \epsilon\to 0 \)
- use Gauss--Bonnet formula to rewrite \( \int_{\Sigma_\epsilon}KdA = 2\pi\chi -
  \int_{\partial\Sigma_\epsilon}\kappa ds \)  where \( \chi \) is Euler characteristic of
  \( \Sigma \) and \( \kappa \) is the geodesic curvature of the boundary curve \(
  \partial\Sigma_{\epsilon} \) w.r.t the surface \( \Sigma_\epsilon \). Then prove that
  the integral \(
  \int_{\partial\Sigma_\epsilon}\kappa ds = \frac{{\rm
  length}(\partial\Sigma_\epsilon)}{\epsilon} + O(\epsilon) \)
Therefore \( \Anorm \) can be expressed as
\[
 \Anorm = -2\pi\chi + \lim_{\epsilon\to 0}(A_\epsilon + K_\epsilon) = -2\pi\chi+ \int_{\Sigma}(1+K)dA
\]
where \( K_\epsilon = \int_{\Sigma_\epsilon}KdA \).


We [[ref:existence-enorm][proved]] that \( E_\epsilon - 2A_\epsilon \) has a finite limit as \( \epsilon\to 0 \),
i.e. \( \Enorm -2 \Anorm = \lim_{\epsilon\to 0} (E_\epsilon - 2A_\epsilon) \)
so \( \Enorm = -4\pi\chi + \lim_{\epsilon\to 0}(E_\epsilon + 2K_\epsilon) \), or
\begin{equation}
\label{eq:enorm-simple}
 \Enorm = -4\pi\chi + \int_\Sigma \left[ 2K(f^*g)\sqrt{{\rm det}_h f^*g} + \tr_h f^*g \right] dA_h
\end{equation}
where \( h \) is the metric on \( \Sigma \), \( g \) is the AH metric on \( M \), \( K(f^*g) \)
is the Gauss curvature of \( (\Sigma, f^*g) \)

#+BEGIN_remark
The expression eqref:eq:enorm-simple does not make it obvious that \( \Enorm \) is
finite. It is however simpler and it allows us to see that \( \Enorm \) only depends on \( f^* g \), the
restriction of \( g \) on the surface, and not the entire metric \( g \).
#+END_remark



** Eells--Sampson with boundary label:Eells-Sampson-bndry
Eells and Sampson proved that the variation of energy \( E = \int_{\Sigma}|df|^2 \) of a
map \( f: (\Sigma,h) \longrightarrow (M,g) \) between Riemannian manifolds without
boundary is given by
\[
 \frac{d}{dt}E(f_t) = \int_\Sigma \left\langle \tau(f_0), \frac{df_t}{dt} \right\rangle_g dV_h
\]
where they applied Stokes' formula once in their computation. 

In case of manifold with
boundary, the variation of \( E \) should be given by
\[
 \frac{d}{dt}E(f_t) = \int_{\Sigma} \left\langle \tau(f_0),\frac{d f_t}{dt}\right
\rangle_g dV_h + 2\int_{\partial\Sigma} \left\langle \frac{\partial f}{\partial n} , \frac{d
f_t}{dt} \right\rangle_g dA_h
\]

In our case, if \( \{f_t\} \) is a perturbation of \( f_0: (\Sigma,h) \longrightarrow
(M,g) \) with the same boundary curve \( \restr{f_t}{\partial\Sigma} \), but not
necessarily of compact support, one has
\begin{equation}
\label{eq:eells-sampson-bndry}
\frac{d E_\epsilon(f_t)}{dt} = \int_{\Sigma_\epsilon} \left \langle\tau(f_0), \frac{d
f_t}{dt} \right \rangle_g dA_h + 2\int_{\partial\Sigma_\epsilon(f_0)} \left\langle
\frac{\partial f_0}{\partial n}, \frac{d f_t}{dt}\right \rangle_g ds_h
\end{equation}
where \( n \) is the outward \( h \)-normal vector of \( \partial\Sigma_\epsilon \) in \(
\Sigma_\epsilon \).

In case of compact perturbation, the boundary term vanishes when \( \epsilon \) is
sufficiently small, it follows that if \( f_0 \) is a critical point of \( \Enorm \) then

\( f_0 \) is harmonic.

** Critical points of \( \Enorm \)
We will prove, modulo a justification to pass the limit inside an integral, that if we
restrict to perturbations \( \{f_t\} \) with vanishing quadratic differential \( q(f_t)_g = 0
\) (the stronger vanishing condition) then \( f_0 \) is a critical point of \( \Enorm \)
if and only if it is harmonic. In fact we will prove that

\begin{equation}
\label{eq:var-Eep}
 \frac{d E_\epsilon(f_t)}{dt} = \int_{\Sigma_\epsilon} \left
 \langle \tau(f_0),\frac{df_t}{dt} \right \rangle_g dA_h
\end{equation}

for any admissible perturbation \( \{f_t\} \). 

Since \( \Enorm = E_\epsilon
 -\frac{l}{\epsilon} + O(\epsilon) \) where \( l \) is the length of the boundary curve,
 by interchanging the limit and integral sign, one sees that \( \frac{d}{dt}\Enorm (f_0) = \lim_{\epsilon\to 0}
 \frac{d}{dt}E_\epsilon(f_0) \), hence any harmonic map is a critical point of \( \Enorm
 \).

#+BEGIN_remark
It follows from the development in our toy model (see the next paragraph) that \( |\frac{df_t}{dt}|_g =
O(\epsilon^2)O(\epsilon^{-1}) = O(\epsilon) \). Let us suppose that \( h  = f^*g \) (since \( E_\epsilon \) is a conformal invariance with respect to \( h \) and the
quadratic differential vanishes near the boundary), then Alexakis--Mazzeo proved that
\( |\tau(f_0)|_g = O(\epsilon) \). Therefore \( \left
 \langle \tau(f_0),\frac{df_t}{dt} \right \rangle_g dA_h = O(1)  \) and the integral on
RHS of eqref:eq:var-Eep is finite.
#+END_remark

#+BEGIN_proof
By eqref:eq:eells-sampson-bndry, we only need to prove that the boundary integral tends to
0 as \( \epsilon \to 0 \). Let us prove this in our toy model \( f_t: \mathbb{H}^2
\longrightarrow \mathbb{H^k} \) where \( \mathbb{H}^2 \) is coordinated by \( (u,s)\in
\mathbb{R}_{\geq 0}\times \mathbb{R} \)
and \( \mathbb{H^k} \) is coordinated by \( (x,y^i)\in \mathbb{R}_{\geq 0}\times
\mathbb{R}^{k-1} \). Suppose that \( f_t \) are given by
\[
 x = au +bu^2 +\dots,\qquad y^i = \gamma^i + W^iu^2 + \dots
\]
where \( b, W^i \) depend on \( t \), \( \gamma^i \) and \( a \) do not depend on \( t \)
because we fixed the boundary curve \( \gamma \) and \( \restr{q(f)_{\bar g}}{\partial
\mathbb{H}^2}=0 \) (the weaker vanishing condition) implies \( a^2 = |\dot\gamma|^2 \). It
follows that \( \frac{df_t}{dt} = u^2 (b_t \frac{\partial}{\partial x} + W^i_t
\frac{\partial}{\partial y^i}) + O(u^3) \).

It is also straightforward to check that \( \frac{\partial f}{\partial n} = a
\frac{\partial}{\partial x}+ O(u) \). Therefore 
\[
 \left \langle \frac{\partial f}{\partial n}, \frac{df_t}{dt} \right \rangle_g = b_t a
O(1) + O(u)
\]

The stronger vanishing condition \( \restr{q(f)_g}{\partial \mathbb{H}^2} \) implies \(
b=0 \) for all admissible \( \{f_t\} \), one has \( b_t=0 \) and therefore \(  \left
\langle \frac{\partial f}{\partial n}, \frac{df_t}{dt} \right \rangle_g= O(u) \). It
follows that the boundary integral in eqref:eq:eells-sampson-bndry tends to \( 0 \) as \(
\epsilon\to 0 \).

#+END_proof




* Existence and invariance by special bdf of the renormalised energy.  label:existence-enorm :noexport:

Let \( f: (\Sigma, \partial\Sigma) \longrightarrow  (M,\partial M) \) be smooth map
from a Riemann surface to an asymptotically hyperbolic manifold \( M \). Let \( r \) be a
special bdf of \( M \), \( \bar g = r^2 g \) be the metric underwhich \( M \) is compact, and \( A_\epsilon(f), E_\epsilon(f) \) be the area and energy of \(
f \) in the region \( r\geq \epsilon \) as a map from \( (\Sigma,h) \) to \( (M,g) \)
for any choice of metric \( h \) in the natural conformal class of \( \Sigma \). 

Denote by 
 - \( q(f)_{g} \) and \( q(f)_{\bar g} = r^2 q(f)_{g} \) the quadratic differentials of \( f \) from the Riemann surface \( \Sigma \) to the Riemannian manifolds \( (M, g) \) and \( (M,\bar g) \) respectively.
 - \( |q(f)_g| \) and \( |q(f)_{\bar g}| \) their norm under \( h \).

We will prove that

#+ATTR_LATEX: :options [Renormalised energy]
#+ATTR_HTML: :id prop:renorm-en :btit (Renormalised energy) 
#+BEGIN_proposition
#+LATEX: \label{prop:renorm-en}
Under no further supposition, one has
\begin{align}
  E_{\epsilon}(f)-2A_\epsilon(f) &= \frac{1}{4} \int_{r\geq\epsilon}\frac{1}{r^2} \frac{|q(f)_{\bar g}|^2}{\tr_h(f^* \bar g) + 2 \sqrt{\det_h(f^* \bar g)}} dA_h \label{eq:en-1}\\
       &= \frac{1}{4}\int_{r\geq\epsilon} \frac{|q(f)_{g}|^2}{\tr_h(f^* g) + 2 \sqrt{\det_h(f^* g)}}dA_h \label{eq:en-2}
\end{align}
One can see from eqref:eq:en-1 that if the quadratic differential of \( f \) vanishes on
\( \partial \Sigma \) then \( |q(f)_{\bar g}|^2 = O(r)^2 \) and the integral increases to
a finite limit as \( \epsilon \to 0 \). Meanwhile eqref:eq:en-2 shows that this limit,
which is the difference between the renormalised energy and renormalised area is
independent of the special bdf \( r \).
#+END_proposition

We remark that the two integrals only depend on the conformal class of \( h \) and the
denominators are sums of densities of energy and area of \( f \) under \( \bar g \) and \(
g \) respectively.

#+BEGIN_proof
It suffices to prove eqref:eq:en-2, which means, at any point \( P \) of \( \Sigma \)
\[
 \tr_h(f^*g)^2 - 4{\rm det}_{h}(f^*g) = \frac{1}{4}|q(f)_g|^2
\]
Under any holomorphic coordinates \( x,y \) centered at \( P \), one has:
\[ 
q(f)_g = \left(\left|\frac{\partial f}{\partial x}\right|^2_g - \left|\frac{\partial f}{\partial y}\right|^2_g - 2i
\langle \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y} \rangle_g\right)
dz\otimes dz\]
hence
\[
\frac{1}{4}\left|q(f)_g\right|^2 = (f^\alpha_x f^\beta_x g_{\alpha\beta} - f^\alpha_y f^\beta_y
g_{\alpha\beta})^2 + 4(f^\alpha_xf^\beta_y g_{\alpha\beta})^2
\]

Moreover
\[
 \tr_h(f^*g) = f^\alpha_x f^\beta_x g_{\alpha\beta} + f^\alpha_y f^\beta_y g_{\alpha\beta}  
\]
and
\[
 {\rm det}_h(f^*g) = f^\alpha_x f^\beta_x g_{\alpha\beta}f^\gamma_yf^\delta_y
g_{\gamma\delta}-f^\alpha_x f^\beta_y g_{\alpha\beta}f^\gamma_xf^\delta_y g_{\gamma\delta}
\]
The result follows.
#+END_proof

Therefore the renormalised energy \( E_{\rm norm} \) is given by 
\begin{align}
   E_{\rm norm} &= 2A_{\rm norm} + \frac{1}{4}\int_\Sigma \frac{|q(f)_g|^2}{\tr_h (f^*g) + 2\sqrt{\det_{h}(f^*g)}}dA_h\\
   	  	&= -4\pi\chi(f(\Sigma)) + \int_{f(\Sigma)}(2W_{1212}+ 2|H|^2 - |\hat k|^2) + \frac{1}{4}\int_\Sigma \frac{|q(f)_g|^2}{\tr_h (f^*g) + 2\sqrt{\det_{h}(f^*g)}}dA_h
\end{align}
according Alexasky-Mazzeo [[https://arxiv.org/abs/0802.2250][formula]] for renormalised area.


#+ATTR_HTML: :id rem:compact-perb
#+BEGIN_remark
#+LATEX: \label{rem:compact-perb}
Let \( \{f_t\} \) be a perturbation of \( f \) with compact support lying outside of
\(r\leq \epsilon_0 \). Then since \( E_\epsilon(f_t) - E_\delta(f_t) =  E_\epsilon(f) -
E_\delta(f) \) for all \( t \), one has
\[
 E_\epsilon(f_t) - E_\epsilon(f) = E_{\rm norm}(f_t) - E_{\rm norm}(f).
\]

Because harmonicity of \( f \) means that \( f \) is critical point of \( E_\epsilon  \) on
\( r\geq \epsilon \) for all \( \epsilon \) arbitrarily closed to 0, it follows that any critical point of \(
E_{\rm norm} \) is harmonic.
#+END_remark





* Log term in energy: half-sphere in \( \mathbb{H}^3 \).  :noexport:
The following example concerns a compact surface (a half-sphere) in \( \mathbb{H}^3 \) (so
there is no subtlety of its boundary in Poincaré's \( \mathbb{H}^3 \) or
\(\mathbb{D}^3\)).

Let \( \mathbb{D}^2 \) be the unit disk coordinated by \( (s,\theta)\in [0,1)\times
[0,2\pi)  \) and \( \mathbb{H}^3 \) be the Poincaré half-space coordinated by \(
(x_0,r,\theta)\in (0,+\infty)\times [0,+\infty)\times [0,2\pi) \). Consider the map \( f:
\mathbb{D}^2 \longrightarrow \mathbb{H}^3 \) given by 
\[
 (s,\theta) \longmapsto \left( \frac{1-s^2}{1+s^2}, (\frac{2s}{1+s^2},\theta) \right)
\]
which is the totally geodesic imbedding of \( (\mathbb{D}^2,\text{Poincaré}) \) into \(
(\mathbb{H}^3,\text{Poincaré}) \). One can verify that if \( g = \frac{1}{x_0^2} (dx_0^2 +
dr^2 + r^2d\theta^2) \) is the Poincaré metric on \( \mathbb{H}^3 \) then
\[
 f^* g = \frac{4}{(1-s^2)^2} (ds^2 + s^2 d\theta^2)
\]
is the Poincaré metric on \( \mathbb{D}^2 \).

We will equip \( \mathbb{D}^2 \) with the following metric
\[
 g_A = dx^2 + dy^2 + 2A dxdy = (1+A\sin 2\theta) ds^2 + s^2 (1-A\sin 2\theta) d\theta^2 +
2As\cos 2\theta ds d\theta
\]
where \( A \) is a suitable smooth function on \( \mathbb{D}^2 \) with \( |A|< 1 \). We
will show that when \( A:=\frac{2s^2}{1+s^4} \) then there will be a \( \ln\epsilon \)
term in the energy of \( f: (\mathbb{D}^2,g_A) \longrightarrow (\mathbb{H}^3,
g=\text{Poincaré}) \).


#+BEGIN_proof
One can check that \( \det
(g_A) = s^2(1-A^2) \) and the contravariant metric is
\[
 (g_A)^{ij} = \frac{1}{s^2 (1-A^2)}\begin{bmatrix}s^2 (1-A\sin 2\theta) & -As\cos 2\theta\\-As\cos 2\theta &
1+A\sin 2\theta\end{bmatrix}
\]

The trace of the pullback metric \( f^*g \) under the metric \( g_A \) is
\[
 \tr_{g_A} (f^*g) = \frac{8}{(1-s^2)^2}.\frac{1}{1-A^2}
\]
Therefore
\[
E_\epsilon(f) := \int_{x_0\geq \epsilon} \tr_{g_A}(f^* g) \sqrt{|\det g_A|} ds d\theta = \int_{x_0\geq
\epsilon} \frac{8}{\sqrt{1-A^2}}.\frac{s}{(1-s^2)^2} ds d\theta
\]


Take \( A:= \frac{2s^2}{1+s^4} \) then \( \sqrt{1-A^2} = \frac{1-s^4}{1+s^4} \) and 
\[
E_\epsilon(f) = 8\pi \int_{y\leq y_{\max}} \frac{1+y^2}{1-y^2}.\frac{1}{(1-y)^2} dy
\]
where \( y=s^2 \) running from \( 0 \) to \( y_{\max}=\frac{1-\epsilon}{1+\epsilon} \).

By writing the rational function as
\[
 \frac{1+y^2}{(1-y^2)(1-y)^2} = -\frac{1}{2} .\frac{1}{(1-y)^2} + \frac{1}{(1-y)^3} +
\frac{1}{4}.\frac{1}{1+y} + \frac{1}{4}.\frac{1}{1-y},
\]
one sees that
\[
 E_\epsilon(f) = \frac{\pi}{\epsilon^2} + \frac{4\pi}{\epsilon} -2\pi \ln\epsilon - 5\pi.
\]
#+END_proof

Let us reuse the formula
\[
 E_\epsilon(f) = \int_{x\geq \epsilon} \frac{8}{\sqrt{1-A^2}} \frac{s}{(1-s^2)^2}dsd\theta
 = 8\pi\int_{z\geq z_{\min}} \frac{1}{B(z)} \frac{1}{z^2}dz
\]
where \( z = 1-s^2 \) running from \( z_{\min} = \frac{2\epsilon}{1+\epsilon} \) to \( 1
\) and \( B = \sqrt{1-A^2} \).

Let us assume that 
 - \( A \) is at least \( C^1 \) on \( z = 1-s^2 \),
 - \( A \) tends to \( 0 \) near the boundary circle, i.e. when \( z\to 0 \),
The second assumption is equivalent to \( B(z=0) = 1 \) and the first assumption at \( z=0
\) (given that the second holds) is equivalent to \( B'(z=0) = 0 \). So \( B = 1 + az^2 + O(z^3) \) 

Trying to integrate \( \frac{1}{z^2 (z-a)(z-b)(z-c)} \) when \( abc=1 \) and \( ab+bc+ca=0
\), one sees that there is no \( \ln z \) term (there may be \( \ln(z+\omega) \) with \(
\omega\ne 0 \) term though).

#+ATTR_HTML: :id rem:cond-A-bndry
#+BEGIN_remark
#+LATEX: \label{rem:cond-A-bndry}
So an appropriate condition to add (so that there is no \( \ln\epsilon \) term in the
energy) is that \( A\to 0 \) near the boundary circle, meaning that \( f \) is 
conformal at the boundary.
#+END_remark



* Log term in energy of \( f: \overline{\mathbb{H}^2} \longrightarrow \overline{\mathbb{H}^{n+1}} \).  :noexport:
Let \(\mathbb{H}^2 \) be coordinated by \( (t,s) \) with \( t>0,s\in \mathbb{R} \) and \( \mathbb{H}^{n+1} \) be cordinated by \( x> 0, y^1,\dots, y^n\in \mathbb{R} \).

Define \( f: \overline{\mathbb{H}^2} \longrightarrow \overline{\mathbb{H}^{n+1}} \) by
\[
(t,s) \mapsto \left(t+t^2, \gamma^i(s)\right)
\]
whose image is the vertical cylinder over the curve \( s \mapsto (\gamma^i(s)) \).

#+BEGIN_exampl
If \( n=2 \), one can take \( (y^1,y^2) := \left(\frac{2s}{s^2+1},\frac{s^2-1}{s^2+1}
\right)  \). Its image is the unit circle in \( \{x=0\} \), only filled once as \( s \)
varies in \( \mathbb{R} \).
#+END_exampl

Now that 
\[
 dx = (1+2t)dt,\quad dy^i = \dot \gamma^i ds,
\]
the pullback by \( f \) of Poincaré metric \( g = \frac{1}{x^2}(dx^2 + \sum d{y^i}^2) \) on \(
\mathbb{H}^{n+1} \) is
\[
 f^* g = \frac{1}{t^2 (1+t)^2} \left( (1+2t)^2 dt^2 + \sum \dot {\gamma^i}^2(s) ds^2 \right)
\]
Its trace w.r.t the Euclidean metric on the half 2-plane is
\[
 \tr f^* g = \frac{(1+2t)^2}{t^2(1+t)^2} + \frac{\varphi(s)}{t^2(1+t)^2}
\]
where \( \varphi \) only depends on \( s \) and can be replaced by \( a^2\varphi \) for
any constant \( a>0 \) when one modifies the boundary curve \( \gamma \to a\gamma \)).

Integrate by \( s\in \mathbb{R} \) and \( t \) in \( (t_{\min},1) \) (we can suppose
\(t\leq 1 \) since we are only interested in the energy near boundary, \( t_{\min} =
\frac{-1 + \sqrt{1+4\epsilon}}{2} = \epsilon + O(\epsilon^2) \)):

\[
 \int_t \frac{1}{t^2} + \frac{1}{(1+t)^2} + \frac{2}{t(1+t)} + \const(\varphi) \left(
 \frac{1}{t^2} - \frac{2}{t(1+t)} + \frac{1}{(1+t)^2} \right)
\]
where \( \const(\varphi) \) can be scaled up \( a^2 \) times when one replaces \( \gamma
 \) by \( a\gamma \). Choose \( a \) so that the term \( \frac{2}{t(1+t)} \) remains,
 which integrates to \( \log t_{\min} = \log(\epsilon) + O(\epsilon) \).


#+ATTR_HTML: :id rem:bndry-condition
#+BEGIN_remark
#+LATEX: \label{rem:bndry-condition}
It is clear that one needs a certain regularity of \( f \) at boundary of the initial
space so that the \( \log\epsilon \) term does not appear. The "Poincaré half-plane to
Poincaré disk" transform is only smooth and diffeomorphic in the interior. The boundary map
\( (y^1,y^2) := \left(\frac{2s}{s^2+1},\frac{s^2-1}{s^2+1} \right) \) in the example above
(\( n=2 \)) is the restriction on boundary of the half-plane-to-disk transform.
#+END_remark


* Commutative diagram in \( \TeX \) revisited 
** xypic and xyJax
To my knowledge, the only way to type commutative diagram on the web is to use ~xyJax~, a
third-party extension of ~MathJax~ that render diagram using ~xypic~. This is also how
[[https://stacks.math.columbia.edu/][Stacks Project]] was set up.

The syntax of ~xypic~ is almost the same as ~tikz-cd~, to a basic user the only difference
is how arrows are typed. I learn ~xypic~ syntax by rewriting a GUI editor for ~tikzcd~ by
[[https://tikzcd.yichuanshen.de][Yichuan Shen]] to output ~xypic~ code. [[https://darknmt.github.io/res/xypic-editor/][Here]] is the ~xypic~ version of the editor. I also
host a copy of the ~tikz-cd~ editor [[http://darknmt.github.io/res/tikzcd-editor][here]].

The configuration of ~xyJax~ or any third-party extension MathJax was not very easy for
 me, since it seems that MathJax CDN no longer hosts third-party extensions. So I have to
 host my own copy of ~xyJax~ and tell MathJax CDN to use it, as indicated in [[http://docs.mathjax.org/en/latest/options/ThirdParty.html][its
 documentation]]. Also, one also has to [[https://github.com/sonoisa/XyJax/blob/master/README.md][reconfig a path]] in ~xyJax~.

To config MathJax in org-mode, apropos ~org-html-mathjax-template~.

* LaTeX in Inkscape: Incompatibility between ~ghostscript~ and ~pstoedit~ <2018-03-30 Fri>
Since Ghostscript 9.22, certain flags (e.g. ~dREALLYDEALYBIND~) are deprecated and ~pstoedit~,
a piece of software that Inkscape uses to render LaTeX, remains unchanged since 2005. This
makes Inkscape users unable use LaTeX. Textext developers claims that they will switch to
~pdf2svg~ frontend in their version 0.8 to avoid this trouble with ~pstoedit~. Meanwhile,
the only solution seems to be downgrade ghostscript to 9.21 each time one uses Inkscape.
In ArchLinux, one can downgrade a package using ~pacman~: 

#+BEGIN_SRC bash
ls /var/cache/pacman/pkg/ | grep ghostscript
pacman -U /var/cache/pacman/pkg/package-old_version.pkg.tar.xz
#+END_SRC

or a AUR package called ~downgrade~

#+BEGIN_SRC bash
downgrade ghostscript
#+END_SRC

I had good experience with both of them (~pacman~ to downgrade ~php~ to be compatible
with ~nextcloud~, and ~downgrade~ for ghostscript)


The problem is well documented [[https://bbs.archlinux.org/viewtopic.php?id=224340][here]] and [[https://bitbucket.org/pitgarbe/textext/issues/48/ghostscript-still-bug-under-linux][here]].

* LaTeX indentation in org-mode <2018-02-20 Tue>
  I was told, in accordance with my experience, that we visually process text better if
  each line in a paragraph is approximately below 80 characters. This fact is also
  omnipresent on the internet, standardized tests, books, etc.. being among the
  fundamentals of web design (except wikipedia, that's why I use Wikiwand).

  In Emacs, the key binding ~M-q~ will execute the ~fill-paragraph~ function that
  automatically shrinks text and insert "soft" newlines to shorten line below a certain
  threshold. This function however does not respect the LaTeX structure, e.g. it inserts
  line break inside inline equation and merge display equation.
  format paragraph.

#+BEGIN_SRC org
  This is a long long long long long long long long long paragraph with equation \( 1+1 = 
  2+0=3-1=4-2 \) with an equation in display \[ 1+ 1 = 2\].
#+END_SRC

The problem has been noticed around the Internet [[https://emacs.stackexchange.com/questions/29122/prevent-fill-paragraph-from-breaking-latex-displayed-equations-in-org-mode][here]] and [[https://emacs.stackexchange.com/questions/34938/is-there-a-fill-paragraph-function-which-tries-to-not-break-subordinate-parenthe?rq=1][there]].  

Meanwhile AucTeX does not have this annoying problem. [[https://www.gnu.org/software/auctex/manual/auctex.html#index-LaTeX_002dfill_002dbreak_002dat_002dseparators][It turns out]] that AUCTeX maps the
~M-q~ key to a different function, called ~LaTeX-fill-paragraph~. So the temporary fix is
to load ~latex.el~ in org-mode and maps ~M-q~ to ~LaTeX-fill-paragraph~

#+BEGIN_SRC org
(load "latex.el")
(global-set-key "\M-q" 'LaTeX-fill-paragraph)
#+END_SRC

* A (decent) map of mathematics <2017-10-17 Tue>

  I saw this [[https://www.flickr.com/photos/95869671@N08/32264483720][map of mathematics]] somewhere on YouTube and then again on the door of
  someone's office at the I2M. Although this map may help popularise mathematics, it
  should raise an eyebrow of a serious math student (or even an attentive highschool
  student, as for example 1 was listed among prime numbers in an earlier version of this
  map).

  For a decent map of Mathematics, made by a mathematician, see [[http://www.math.unm.edu/~buium/mapp.pdf][this]].

* My 2016-2017 internship <2017-07-31 Mon> 

I have just recently finished my Stage3A at [[https://www.i2m.univ-amu.fr/][Institut de Mathématiques de Marseille]]. It is
also in this period that I start this blog. The memoire can be founded here [[[../res/Stage2017.pdf][PDF]]]


#+LATEX:\iffalse
bibliographystyle:alpha
bibliography:../res/GeoDiff.bib
#+LATEX:\fi
